import { notFound } from 'next/navigation'
import Link from 'next/link'
import WorkforceHeading from '../../../_components/PageHeading'
import { createSupabaseAdminClient } from '@/lib/supabase'
import { getCallerPermissions } from '@/lib/admin-auth'
import { requireRecruitmentAccess } from '@/lib/recruitment-auth'
import { addApplicationNote, approveApplicationMessage, composeApplicationMessage, createAssessment, createInterview, createOffer, transitionApplication } from '../actions'

const ACTIVE_STAGES = [
  ['under_review', 'Under review'], ['eligibility_review', 'Eligibility review'],
  ['screening', 'Recruiter screening'], ['hiring_manager_review', 'Hiring manager review'],
  ['assessment', 'Assessment'], ['interview', 'Interview'], ['final_interview', 'Final interview'],
  ['reference_check', 'References / checks'], ['offer', 'Offer'], ['on_hold', 'On hold'],
]

export default async function ApplicationDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const access = await requireRecruitmentAccess({ entityType: 'application', entityId: id, allowedPermissions: ['workforce.applications.read'] })
  const supabase = createSupabaseAdminClient()
  let notesQuery = supabase.from('recruitment_candidate_notes').select('id, body, visibility, created_at, author_employee_id, workforce_employees(full_name)').eq('application_id', id).order('created_at', { ascending: false })
  notesQuery = access.employeeId ? notesQuery.or(`visibility.neq.private,author_employee_id.eq.${access.employeeId}`) : notesQuery.neq('visibility', 'private')
  const [applicationResult, historyResult, notesResult, answersResult, interviewResult, assessmentResult, offerResult, reasonsResult, messagesResult, permissions] = await Promise.all([
    supabase.from('recruitment_applications').select('*, recruitment_candidates(*), workforce_jobs(id, title, department, location, slug)').eq('id', id).maybeSingle(),
    supabase.from('recruitment_application_stage_history').select('id, from_status, to_status, candidate_facing_status, reason_code, note, changed_by_actor_type, created_at').eq('application_id', id).order('created_at', { ascending: false }),
    notesQuery,
    supabase.from('recruitment_application_answers').select('id, question_label, answer').eq('application_id', id).order('created_at'),
    supabase.from('recruitment_interviews').select('id, title, status, starts_at, interview_type').eq('application_id', id).order('starts_at'),
    supabase.from('recruitment_assessments').select('id, title, status, score, max_score, due_at').eq('application_id', id).order('created_at'),
    supabase.from('recruitment_offers').select('id, offer_number, status, version, start_date, expires_at, base_salary, currency').eq('application_id', id).order('created_at', { ascending: false }),
    supabase.from('recruitment_disposition_reasons').select('code, label, category').eq('is_active', true).order('sort_order'),
    supabase.from('recruitment_messages').select('id, channel, direction, subject, body, status, scheduled_for, approval_status, sent_by, created_at, recruitment_message_recipients(address, delivery_status)').eq('application_id', id).order('created_at', { ascending: false }).limit(100),
    getCallerPermissions(),
  ])
  for (const result of [applicationResult, historyResult, notesResult, answersResult, interviewResult, assessmentResult, offerResult, reasonsResult, messagesResult]) {
    if (result.error) throw result.error
  }
  if (!applicationResult.data) notFound()
  const application = applicationResult.data
  const candidate = Array.isArray(application.recruitment_candidates) ? application.recruitment_candidates[0] : application.recruitment_candidates
  const job = Array.isArray(application.workforce_jobs) ? application.workforce_jobs[0] : application.workforce_jobs
  const canAdvance = permissions.has('workforce.applications.advance')
  const canReject = permissions.has('workforce.applications.reject')
  const canNote = permissions.has('workforce.candidates.write')
  const canSeeSensitive = permissions.has('workforce.candidates.export') || permissions.has('recruitment.candidate.sensitive')
  const canSeeCompensation = permissions.has('workforce.offers.compensation_read')
  const canScheduleInterview = permissions.has('workforce.interviews.schedule')
  const canCreateOffer = permissions.has('workforce.offers.create') && (offerResult.data?.length ?? 0) === 0 && ['final_interview', 'reference_check', 'offer'].includes(application.status)
  const canCreateAssessment = permissions.has('workforce.assessments.write')
  const canCommunicate = permissions.has('workforce.recruitment.write')
  const transitionAction = transitionApplication.bind(null, id)
  const noteAction = addApplicationNote.bind(null, id)

  return (
    <>
      <WorkforceHeading title={candidate?.full_name ?? 'Application'} subtitle={`${application.application_reference} · ${job?.title ?? 'Job'} · ${application.candidate_facing_status}`} />
      <div className="grid gap-5 xl:grid-cols-[1fr_380px]">
        <div className="space-y-5">
          <section className="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm">
            <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-gray-400">Internal stage</p><p className="mt-1 text-xl font-semibold capitalize text-gray-950">{application.status.replaceAll('_', ' ')}</p><p className="mt-1 text-sm text-gray-500">Candidate sees: {application.candidate_facing_status}</p></div><span className="rounded-full bg-[#F2E8F6] px-3 py-1 text-xs font-semibold text-[#5B2D8E]">{application.source}</span></div>
            <dl className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{[
              ['Email', candidate?.primary_email], ['Phone', candidate?.phone ?? 'Not provided'], ['Location', [candidate?.city, candidate?.country].filter(Boolean).join(', ') || 'Not provided'],
              ['Current role', candidate?.current_position ?? 'Not provided'], ['Organization', candidate?.current_organization ?? 'Not provided'], ['Experience', candidate?.years_experience == null ? 'Not provided' : `${candidate.years_experience} years`],
              ['Applied', application.submitted_at ? new Date(application.submitted_at).toLocaleDateString('en-TZ') : 'Draft'], ['Work authorized', application.work_authorized == null ? 'Not answered' : application.work_authorized ? 'Yes' : 'No'], ['Weekend availability', application.weekend_available == null ? 'Not answered' : application.weekend_available ? 'Yes' : 'No'],
            ].map(([label, value]) => <div key={label}><dt className="text-xs font-semibold uppercase tracking-wider text-gray-400">{label}</dt><dd className="mt-1 text-sm font-medium text-gray-800">{value}</dd></div>)}</dl>
            {canSeeSensitive && <div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-xs font-semibold uppercase tracking-wider text-amber-800">Restricted candidate data</p><p className="mt-2 text-sm text-amber-950">Salary expectation: {application.salary_expectation ?? 'Not provided'} · Earliest start: {application.earliest_start_date ?? 'Not provided'}</p></div>}
          </section>

          {(answersResult.data ?? []).length > 0 && <section className="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm"><h2 className="text-base font-semibold text-gray-950">Screening answers</h2><dl className="mt-4 divide-y divide-gray-100">{(answersResult.data ?? []).map((answer) => <div key={answer.id} className="py-3"><dt className="text-sm font-semibold text-gray-700">{answer.question_label}</dt><dd className="mt-1 text-sm text-gray-500">{typeof answer.answer === 'string' ? answer.answer : JSON.stringify(answer.answer)}</dd></div>)}</dl></section>}

          <section className="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm"><h2 className="text-base font-semibold text-gray-950">Interviews and assessments</h2>{canScheduleInterview && <form action={createInterview.bind(null, id)} className="mt-4 grid gap-2 rounded-xl bg-violet-50 p-3 sm:grid-cols-[1fr_160px_auto]"><input name="title" required minLength={3} placeholder="Interview title" className="rounded-lg border border-violet-100 bg-white px-3 py-2 text-sm" /><select name="interview_type" className="rounded-lg border border-violet-100 bg-white px-3 py-2 text-sm"><option value="phone">Phone screen</option><option value="video">Video interview</option><option value="onsite">On-site interview</option><option value="panel">Panel interview</option><option value="working_session">Practical session</option><option value="other">Other</option></select><button className="rounded-lg bg-[#5B2D8E] px-4 py-2 text-xs font-semibold text-white">Create draft</button></form>}<div className="mt-4 grid gap-3 md:grid-cols-2">{(interviewResult.data ?? []).map((interview) => <Link key={interview.id} href={`/workforce/recruitment/interviews/${interview.id}`} className="rounded-xl bg-gray-50 p-4 hover:bg-violet-50"><p className="font-semibold text-gray-900">{interview.title}</p><p className="mt-1 text-xs capitalize text-gray-500">{interview.status} · {interview.interview_type}</p><p className="mt-2 text-sm text-gray-600">{interview.starts_at ? new Date(interview.starts_at).toLocaleString('en-TZ') : 'Not scheduled'}</p></Link>)}{(assessmentResult.data ?? []).map((assessment) => <Link key={assessment.id} href={`/workforce/recruitment/assessments/${assessment.id}`} className="rounded-xl bg-gray-50 p-4 hover:bg-sky-50"><p className="font-semibold text-gray-900">{assessment.title}</p><p className="mt-1 text-xs capitalize text-gray-500">{assessment.status}</p><p className="mt-2 text-sm text-gray-600">{assessment.score == null ? (assessment.due_at ? `Due ${new Date(assessment.due_at).toLocaleDateString('en-TZ')}` : 'Awaiting assignment') : `Score ${assessment.score}/${assessment.max_score ?? '—'}`}</p></Link>)}</div>{interviewResult.data?.length === 0 && assessmentResult.data?.length === 0 && <p className="mt-4 text-sm text-gray-400">No interviews or assessments yet.</p>}</section>
          {canCreateAssessment && <section className="rounded-2xl border border-sky-100 bg-sky-50 p-5"><h2 className="font-semibold text-sky-950">Request assessment</h2><form action={createAssessment.bind(null, id)} className="mt-4 grid gap-3 sm:grid-cols-2"><input name="title" required minLength={3} placeholder="Assessment title" className="rounded-lg border border-sky-200 bg-white px-3 py-2 text-sm" /><select name="assessment_type" className="rounded-lg border border-sky-200 bg-white px-3 py-2 text-sm"><option>Written assignment</option><option>Technical test</option><option>Portfolio submission</option><option>Presentation</option><option>Case study</option><option>Event planning simulation</option><option>Video response</option><option>Data exercise</option><option>Practical field assessment</option></select><input name="due_on" type="date" required min={new Date().toISOString().slice(0, 10)} className="rounded-lg border border-sky-200 bg-white px-3 py-2 text-sm" /><input name="time_limit_minutes" type="number" min="0" max="1440" placeholder="Time limit in minutes" className="rounded-lg border border-sky-200 bg-white px-3 py-2 text-sm" /><textarea name="instructions" required rows={3} placeholder="Instructions and submission expectations" className="rounded-lg border border-sky-200 bg-white px-3 py-2 text-sm sm:col-span-2" /><button className="rounded-lg bg-sky-700 px-4 py-2 text-xs font-semibold text-white sm:col-span-2">Send assessment task</button></form></section>}

          <section className="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm"><h2 className="text-base font-semibold text-gray-950">Notes</h2>{canNote && <form action={noteAction} className="mt-4 space-y-2"><textarea name="body" required rows={3} className="w-full rounded-xl border border-gray-200 px-3 py-2 text-sm outline-none focus:border-[#7E5896] focus:ring-2 focus:ring-[#E8D4F1]" placeholder="Evidence, context or follow-up…" /><div className="flex justify-between gap-3"><select name="visibility" className="rounded-lg border border-gray-200 px-3 py-2 text-xs"><option value="recruiting_team">Recruiting team</option><option value="hiring_team">Hiring team</option><option value="private">Private</option></select><button className="rounded-lg bg-black px-4 py-2 text-xs font-semibold text-white">Add note</button></div></form>}<div className="mt-4 divide-y divide-gray-100">{(notesResult.data ?? []).map((note) => { const author = Array.isArray(note.workforce_employees) ? note.workforce_employees[0] : note.workforce_employees; return <article key={note.id} className="py-4"><div className="flex justify-between gap-3 text-xs text-gray-400"><span>{author?.full_name ?? 'Team member'} · {note.visibility.replaceAll('_', ' ')}</span><time>{new Date(note.created_at).toLocaleString('en-TZ')}</time></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-gray-600">{note.body}</p></article> })}</div></section>
          <section className="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm"><h2 className="text-base font-semibold text-gray-950">Communications</h2><p className="mt-1 text-sm text-gray-500">Every outbound message and delivery state remains attached to this application.</p>{canCommunicate && <form action={composeApplicationMessage.bind(null, id)} className="mt-4 grid gap-2 rounded-xl bg-gray-50 p-4 sm:grid-cols-2"><select name="channel" className="rounded-lg border border-gray-200 bg-white px-3 py-2 text-sm"><option value="email">Email</option><option value="in_app">Candidate portal</option><option value="sms">SMS (enabled + consent)</option><option value="whatsapp">WhatsApp (integrated + consent)</option><option value="phone_log">Phone-call log</option></select><input name="subject" placeholder="Subject" className="rounded-lg border border-gray-200 px-3 py-2 text-sm" /><textarea name="body" required rows={5} placeholder="Candidate-facing message or call summary" className="rounded-lg border border-gray-200 px-3 py-2 text-sm sm:col-span-2" /><label className="text-xs font-semibold text-gray-600">Schedule<input name="scheduled_for" type="datetime-local" className="mt-1 w-full rounded-lg border border-gray-200 px-3 py-2 text-sm" /></label><label className="flex items-center gap-2 text-xs font-semibold text-gray-600"><input type="checkbox" name="approval_required" /> Require another reviewer before sending</label><button className="rounded-lg bg-[#5B2D8E] px-4 py-2 text-xs font-semibold text-white sm:col-span-2">Queue or log message</button></form>}<div className="mt-4 space-y-3">{(messagesResult.data ?? []).map((message) => <article key={message.id} className="rounded-xl border border-gray-100 p-4"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-semibold capitalize">{message.channel.replaceAll('_', ' ')} · {message.subject || 'No subject'}</p><span className="text-xs capitalize text-gray-500">{message.status} · approval {message.approval_status}</span></div><p className="mt-2 whitespace-pre-wrap text-sm text-gray-600">{message.body}</p><p className="mt-2 text-xs text-gray-400">{new Date(message.created_at).toLocaleString('en-TZ')}{message.scheduled_for ? ` · scheduled ${new Date(message.scheduled_for).toLocaleString('en-TZ')}` : ''}</p>{canCommunicate && message.approval_status === 'pending' && message.sent_by !== access.employeeId && <div className="mt-3 flex gap-2"><form action={approveApplicationMessage.bind(null, id, message.id, 'approved')}><button className="rounded-lg bg-emerald-700 px-3 py-1.5 text-xs font-semibold text-white">Approve</button></form><form action={approveApplicationMessage.bind(null, id, message.id, 'rejected')}><button className="rounded-lg bg-rose-100 px-3 py-1.5 text-xs font-semibold text-rose-900">Reject</button></form></div>}</article>)}</div></section>
        </div>

        <aside className="space-y-5">
          {canAdvance && <section className="rounded-2xl border border-[#E8D4F1] bg-[#FBF7FD] p-5 shadow-sm"><h2 className="font-semibold text-gray-950">Move application</h2><form action={transitionAction} className="mt-4 space-y-3"><select name="target_status" className="w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm">{ACTIVE_STAGES.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><textarea name="note" rows={2} placeholder="Transition note (optional)" className="w-full rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm" /><button className="w-full rounded-xl bg-[#5B2D8E] px-4 py-2.5 text-sm font-semibold text-white">Save stage</button></form></section>}
          {canReject && <section className="rounded-2xl border border-rose-200 bg-rose-50 p-5 shadow-sm"><h2 className="font-semibold text-rose-950">Structured rejection</h2><form action={transitionAction} className="mt-4 space-y-3"><input type="hidden" name="target_status" value="rejected" /><select name="reason_code" required className="w-full rounded-xl border border-rose-200 bg-white px-3 py-2.5 text-sm"><option value="">Choose internal reason</option>{(reasonsResult.data ?? []).map((reason) => <option key={reason.code} value={reason.code}>{reason.label}</option>)}</select><textarea name="note" required rows={3} placeholder="Internal decision evidence" className="w-full rounded-xl border border-rose-200 bg-white px-3 py-2 text-sm" /><button className="w-full rounded-xl bg-rose-700 px-4 py-2.5 text-sm font-semibold text-white">Reject application</button></form></section>}
          <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><h2 className="font-semibold text-gray-950">Offers</h2><div className="mt-3 space-y-3">{(offerResult.data ?? []).map((offer) => <Link key={offer.id} href={`/workforce/recruitment/offers/${offer.id}`} className="block rounded-xl bg-gray-50 p-3 hover:bg-violet-50"><div className="flex justify-between gap-2"><span className="text-sm font-semibold">{offer.offer_number}</span><span className="text-xs capitalize text-gray-500">{offer.status}</span></div><p className="mt-1 text-xs text-gray-500">Version {offer.version} · starts {offer.start_date ?? 'TBD'}</p>{canSeeCompensation && <p className="mt-2 text-sm font-semibold text-gray-800">{offer.currency} {Number(offer.base_salary).toLocaleString()}</p>}</Link>)}{offerResult.data?.length === 0 && <p className="text-sm text-gray-400">No offers yet.</p>}</div></section>
          {canCreateOffer && <section className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5 shadow-sm"><h2 className="font-semibold text-emerald-950">Create offer draft</h2><form action={createOffer.bind(null, id)} className="mt-4 space-y-3"><label className="block text-xs font-semibold text-emerald-900">Base salary (TZS)<input name="base_salary" type="number" min="0" step="1" required className="mt-1 w-full rounded-lg border border-emerald-200 bg-white px-3 py-2 text-sm" /></label><div className="grid grid-cols-2 gap-2"><label className="text-xs font-semibold text-emerald-900">Start date<input name="start_date" type="date" required min={new Date().toISOString().slice(0, 10)} className="mt-1 w-full rounded-lg border border-emerald-200 bg-white px-3 py-2 text-sm" /></label><label className="text-xs font-semibold text-emerald-900">Expires on<input name="expires_on" type="date" required min={new Date().toISOString().slice(0, 10)} className="mt-1 w-full rounded-lg border border-emerald-200 bg-white px-3 py-2 text-sm" /></label></div><label className="block text-xs font-semibold text-emerald-900">Working hours<input name="working_hours" defaultValue="40 hours per week" className="mt-1 w-full rounded-lg border border-emerald-200 bg-white px-3 py-2 text-sm" /></label><label className="block text-xs font-semibold text-emerald-900">Probation terms<input name="probation_terms" placeholder="For example: six months" className="mt-1 w-full rounded-lg border border-emerald-200 bg-white px-3 py-2 text-sm" /></label><label className="block text-xs font-semibold text-emerald-900">Conditions<textarea name="conditions" rows={3} placeholder="One condition per line" className="mt-1 w-full rounded-lg border border-emerald-200 bg-white px-3 py-2 text-sm" /></label><input type="hidden" name="pay_frequency" value="monthly" /><button className="w-full rounded-lg bg-emerald-700 px-4 py-2.5 text-xs font-semibold text-white">Create governed draft</button></form></section>}
          <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><h2 className="font-semibold text-gray-950">Activity</h2><ol className="mt-3 space-y-3">{(historyResult.data ?? []).map((event) => <li key={event.id} className="border-l-2 border-gray-200 pl-3"><p className="text-sm font-semibold capitalize text-gray-800">{event.to_status.replaceAll('_', ' ')}</p><p className="mt-0.5 text-xs text-gray-400">{new Date(event.created_at).toLocaleString('en-TZ')} · {event.changed_by_actor_type}</p></li>)}</ol></section>
        </aside>
      </div>
    </>
  )
}
