import { toast } from 'sonner'
import type { StoredOrder } from '@/lib/cart-storage'

/**
 * Downloads the branded invoice as a real PDF generated by /api/invoice.
 *
 * The previous implementation printed a hidden iframe and relied on the
 * browser's "Save as PDF" print dialog — desktop-only: Android Chrome ignores
 * programmatic sub-frame printing, and in-app WebViews (WhatsApp/Instagram,
 * where most customers open OpusPass) have no print UI at all, so the button
 * silently did nothing on phones.
 *
 * Delivery is layered for device coverage:
 *  1. Touch devices with Web Share file support get the native share sheet
 *     (save to Files, send to WhatsApp, etc.).
 *  2. Everything else — including old WebViews without Blob-URL download
 *     support — gets a hidden-iframe form POST, which hands the
 *     `Content-Disposition: attachment` response to the browser's own
 *     download manager.
 */
export async function downloadInvoice(order: StoredOrder): Promise<void> {
  if (typeof document === 'undefined') return

  const noun = order.documentKind === 'quotation' ? 'quotation' : 'invoice'

  // Quotations render through the same route and the same document, so they
  // ride this delivery ladder too — they only differ in what they are called.
  const kind = order.documentKind === 'quotation' ? 'Quotation' : 'Invoice'
  const filename = `OpusFesta-${kind}-${order.ref.replace(/[^A-Za-z0-9_-]/g, '') || 'order'}.pdf`

  const isTouch =
    typeof window.matchMedia === 'function' &&
    (window.matchMedia('(pointer: coarse)').matches || navigator.maxTouchPoints > 0)

  if (isTouch && typeof navigator.canShare === 'function') {
    try {
      const res = await fetch('/api/invoice', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(order),
      })
      if (!res.ok) {
        // The form fallback would hit the same server error invisibly — tell
        // the user instead. (Network exceptions still fall through: the form
        // POST goes via the browser's own navigation stack, which can succeed
        // where fetch is blocked.)
        toast.error(`Could not download the ${noun}`, {
          description: 'Please try again, or contact us on WhatsApp at +255 799 202 171.',
        })
        return
      }
      const blob = await res.blob()
      const file = new File([blob], filename, { type: 'application/pdf' })
      if (navigator.canShare({ files: [file] })) {
        await navigator.share({ files: [file], title: filename })
        return
      }
    } catch (err) {
      // User dismissed the share sheet — not an error, and nothing to download.
      if (err instanceof DOMException && err.name === 'AbortError') return
      // Share unsupported/blocked or fetch hiccup — fall through to the form POST.
    }
  }

  submitDownloadForm(order, noun)
}

/**
 * Top-level navigation POST into a hidden iframe: the attachment response is
 * handled by the browser's native download path, which works even where
 * `navigator.share` and Blob-URL anchors don't (older Android WebViews).
 */
function submitDownloadForm(order: StoredOrder, noun: string): void {
  const frameName = `invoice-dl-${Date.now()}`
  const iframe = document.createElement('iframe')
  iframe.name = frameName
  iframe.setAttribute('aria-hidden', 'true')
  iframe.style.display = 'none'

  const form = document.createElement('form')
  form.method = 'POST'
  form.action = '/api/invoice'
  form.target = frameName
  form.style.display = 'none'

  const field = document.createElement('input')
  field.type = 'hidden'
  field.name = 'order'
  field.value = JSON.stringify(order)
  form.appendChild(field)

  document.body.appendChild(iframe)
  document.body.appendChild(form)

  try {
    form.submit()
  } catch {
    toast.error(`Could not download the ${noun}`, {
      description: 'Please try again, or contact us on WhatsApp at +255 799 202 171.',
    })
  } finally {
    form.remove()
    // Give the download plenty of time to be handed off before removing the frame.
    window.setTimeout(() => iframe.remove(), 60_000)
  }
}
