import Link from 'next/link'
import WorkforceHeading from '../../_components/PageHeading'
import { getCallerPermissions, requirePermission } from '@/lib/admin-auth'
import { createSupabaseAdminClient } from '@/lib/supabase'
import { getRecruitmentScope } from '../_lib/queries'
import { mergeCandidates, reviewDuplicateMatch } from './actions'

const NONE = ['00000000-0000-0000-0000-000000000000']
function param(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] ?? '' : value ?? '' }

export default async function CandidatesPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requirePermission('workforce.candidates.read'); const [scope, permissions, params] = await Promise.all([getRecruitmentScope(), getCallerPermissions(), searchParams]); const db = createSupabaseAdminClient()
  let scopedIds: string[] | null = null; if (!scope.organizationWide) { const result = scope.applicationIds.length ? await db.from('recruitment_applications').select('candidate_id').in('id', scope.applicationIds) : { data: [], error: null }; if (result.error) throw result.error; scopedIds = [...new Set((result.data ?? []).map((row) => row.candidate_id))] }
  let candidateQuery = db.from('recruitment_candidates').select('id, full_name, preferred_name, primary_email, phone, city, country, current_position, current_organization, linkedin_url, status, source_summary, last_activity_at').neq('status', 'deleted').order('last_activity_at', { ascending: false }).limit(1000); if (scopedIds) candidateQuery = candidateQuery.in('id', scopedIds.length ? scopedIds : NONE)
  const candidates = await candidateQuery; if (candidates.error) throw candidates.error; const ids = (candidates.data ?? []).map((candidate) => candidate.id)
  const [applications, skills, tags, memberships, duplicates] = await Promise.all([
    ids.length ? db.from('recruitment_applications').select('id, candidate_id, application_reference, status, source, workforce_jobs(title)').in('candidate_id', ids) : Promise.resolve({ data: [], error: null }),
    ids.length ? db.from('recruitment_candidate_skills').select('candidate_id, skill, proficiency').in('candidate_id', ids) : Promise.resolve({ data: [], error: null }),
    ids.length ? db.from('recruitment_candidate_tags').select('candidate_id, recruitment_tags(name)').in('candidate_id', ids) : Promise.resolve({ data: [], error: null }),
    ids.length ? db.from('recruitment_talent_pool_members').select('candidate_id, recruitment_talent_pools(name)').in('candidate_id', ids).eq('status', 'active') : Promise.resolve({ data: [], error: null }),
    permissions.has('workforce.candidates.merge') && ids.length ? db.from('recruitment_duplicate_matches').select('*').or(`candidate_id.in.(${ids.join(',')}),possible_duplicate_id.in.(${ids.join(',')})`).eq('status', 'pending').order('confidence', { ascending: false }) : Promise.resolve({ data: [], error: null }),
  ]); for (const result of [applications, skills, tags, memberships, duplicates]) if (result.error) throw result.error
  const q = param(params.q).toLowerCase(); const skill = param(params.skill).toLowerCase(); const location = param(params.location).toLowerCase(); const status = param(params.status); const source = param(params.source).toLowerCase(); const stage = param(params.stage)
  const filtered = (candidates.data ?? []).filter((candidate) => { const apps = (applications.data ?? []).filter((app) => app.candidate_id === candidate.id); const candidateSkills = (skills.data ?? []).filter((item) => item.candidate_id === candidate.id).map((item) => item.skill); const candidateTags = (tags.data ?? []).filter((item) => item.candidate_id === candidate.id).map((item) => { const tag = Array.isArray(item.recruitment_tags) ? item.recruitment_tags[0] : item.recruitment_tags; return tag?.name ?? '' }); const pools = (memberships.data ?? []).filter((item) => item.candidate_id === candidate.id).map((item) => { const pool = Array.isArray(item.recruitment_talent_pools) ? item.recruitment_talent_pools[0] : item.recruitment_talent_pools; return pool?.name ?? '' }); const haystack = [candidate.full_name, candidate.primary_email, candidate.phone, candidate.current_position, candidate.current_organization, candidate.city, candidate.country, candidate.linkedin_url, ...candidateSkills, ...candidateTags, ...pools, ...apps.map((app) => app.application_reference), ...apps.map((app) => { const job = Array.isArray(app.workforce_jobs) ? app.workforce_jobs[0] : app.workforce_jobs; return job?.title ?? '' })].join(' ').toLowerCase(); return (!q || haystack.includes(q)) && (!skill || candidateSkills.some((value) => value.toLowerCase().includes(skill))) && (!location || `${candidate.city} ${candidate.country}`.toLowerCase().includes(location)) && (!status || candidate.status === status) && (!source || apps.some((app) => app.source.toLowerCase().includes(source))) && (!stage || apps.some((app) => app.status === stage)) })
  const compareRaw = params.compare; const compareIds = (Array.isArray(compareRaw) ? compareRaw : typeof compareRaw === 'string' ? compareRaw.split(',') : []).slice(0, 4); const compared = filtered.filter((candidate) => compareIds.includes(candidate.id)); const nameMap = new Map((candidates.data ?? []).map((candidate) => [candidate.id, candidate.full_name]))
  return <><WorkforceHeading title="Candidate search" subtitle="Search name, contacts, skills, employer, role, reference, job, location, tags, pools, source and stage within your hiring scope." /><form className="grid gap-2 rounded-2xl border bg-white p-4 md:grid-cols-3 xl:grid-cols-6"><input name="q" defaultValue={q} placeholder="Search everything" className="rounded-lg border px-3 py-2 text-sm" /><input name="skill" defaultValue={skill} placeholder="Skill" className="rounded-lg border px-3 py-2 text-sm" /><input name="location" defaultValue={location} placeholder="Location" className="rounded-lg border px-3 py-2 text-sm" /><select name="status" defaultValue={status} className="rounded-lg border px-3 py-2 text-sm"><option value="">All statuses</option><option value="active">Active</option><option value="talent_pool">Talent pool</option><option value="hired">Hired</option><option value="do_not_contact">Do not contact</option></select><input name="source" defaultValue={source} placeholder="Source" className="rounded-lg border px-3 py-2 text-sm" /><select name="stage" defaultValue={stage} className="rounded-lg border px-3 py-2 text-sm"><option value="">All stages</option>{['submitted', 'screening', 'assessment', 'interview', 'final_interview', 'reference_check', 'offer', 'hired', 'rejected', 'withdrawn'].map((value) => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select><button className="rounded-lg bg-[#5B2D8E] px-4 py-2 text-xs font-semibold text-white xl:col-span-6">Search candidates</button></form>
    <form className="mt-5"><div className="flex items-center justify-between"><p className="text-sm text-gray-500">{filtered.length} candidates · select up to four to compare</p><button className="rounded-lg border bg-white px-3 py-2 text-xs font-semibold">Compare selected</button></div><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map((candidate) => { const candidateSkills = (skills.data ?? []).filter((item) => item.candidate_id === candidate.id); const apps = (applications.data ?? []).filter((app) => app.candidate_id === candidate.id); return <article key={candidate.id} className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div><Link href={`/workforce/recruitment/candidates/${candidate.id}`} className="font-semibold hover:underline">{candidate.full_name}</Link><p className="mt-1 text-xs text-gray-500">{candidate.primary_email}{candidate.city ? ` · ${candidate.city}` : ''}</p></div><input type="checkbox" name="compare" value={candidate.id} defaultChecked={compareIds.includes(candidate.id)} aria-label={`Compare ${candidate.full_name}`} /></div><p className="mt-3 text-sm">{[candidate.current_position, candidate.current_organization].filter(Boolean).join(' at ') || 'Profile details pending'}</p><div className="mt-3 flex flex-wrap gap-1">{candidateSkills.slice(0, 6).map((item) => <span key={item.skill} className="rounded-full bg-violet-50 px-2 py-1 text-xs text-violet-800">{item.skill}</span>)}</div><p className="mt-3 text-xs capitalize text-gray-400">{candidate.status.replaceAll('_', ' ')} · {apps.length} application{apps.length === 1 ? '' : 's'}</p></article> })}</div></form>
    {compared.length > 1 && <section className="mt-5 overflow-x-auto rounded-2xl border bg-white p-5"><h2 className="font-semibold">Candidate comparison</h2><table className="mt-3 w-full min-w-[700px] text-left text-sm"><thead><tr><th className="p-2">Field</th>{compared.map((candidate) => <th key={candidate.id} className="p-2"><Link href={`/workforce/recruitment/candidates/${candidate.id}`} className="underline">{candidate.full_name}</Link></th>)}</tr></thead><tbody>{([['Current role', (id: string) => { const candidate = compared.find((item) => item.id === id)!; return [candidate.current_position, candidate.current_organization].filter(Boolean).join(' at ') || '—' }], ['Location', (id: string) => { const candidate = compared.find((item) => item.id === id)!; return [candidate.city, candidate.country].filter(Boolean).join(', ') || '—' }], ['Skills', (id: string) => (skills.data ?? []).filter((item) => item.candidate_id === id).map((item) => item.skill).join(', ') || '—'], ['Applications', (id: string) => (applications.data ?? []).filter((item) => item.candidate_id === id).map((item) => item.status.replaceAll('_', ' ')).join(', ') || '—']] as const).map(([label, getter]) => <tr key={label} className="border-t"><th className="p-2 text-xs text-gray-500">{label}</th>{compared.map((candidate) => <td key={candidate.id} className="p-2">{getter(candidate.id)}</td>)}</tr>)}</tbody></table></section>}
    {permissions.has('workforce.candidates.merge') && <section className="mt-5 rounded-2xl border border-amber-100 bg-amber-50 p-5"><h2 className="font-semibold text-amber-950">Duplicate review—never automatic</h2><div className="mt-3 space-y-2">{(duplicates.data ?? []).map((match) => <div key={match.id} className="rounded-xl bg-white p-3"><p className="text-sm font-semibold">{nameMap.get(match.candidate_id)} ↔ {nameMap.get(match.possible_duplicate_id)}</p><p className="text-xs text-gray-500">Matched: {match.matched_fields.join(', ')} · confidence {match.confidence == null ? '—' : `${Math.round(Number(match.confidence) * 100)}%`}</p><div className="mt-2 flex gap-2"><form action={reviewDuplicateMatch.bind(null, match.id, 'confirmed_duplicate')}><button className="rounded-lg border px-2 py-1 text-xs">Confirm for merge review</button></form><form action={reviewDuplicateMatch.bind(null, match.id, 'not_duplicate')}><button className="rounded-lg border px-2 py-1 text-xs">Not a duplicate</button></form></div></div>)}</div><form action={mergeCandidates} className="mt-4 grid gap-2 md:grid-cols-4"><select name="surviving_candidate_id" required className="rounded-lg border px-3 py-2 text-sm"><option value="">Surviving profile</option>{filtered.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.full_name} · {candidate.primary_email}</option>)}</select><select name="merged_candidate_id" required className="rounded-lg border px-3 py-2 text-sm"><option value="">Profile to merge</option>{filtered.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.full_name} · {candidate.primary_email}</option>)}</select><input name="reason" required minLength={5} placeholder="Reviewed merge reason" className="rounded-lg border px-3 py-2 text-sm" /><button className="rounded-lg bg-amber-900 px-3 py-2 text-xs font-semibold text-white">Merge atomically</button></form></section>}
  </>
}
