import WorkforceHeading from '../../_components/PageHeading'
import { requirePermission } from '@/lib/admin-auth'
import { createSupabaseAdminClient } from '@/lib/supabase'
import { createMessageTemplate, sendTemplateTest, setMessageTemplateStatus, updateMessageTemplate } from './actions'

const input = 'w-full rounded-lg border border-gray-200 bg-white px-3 py-2 text-sm'

export default async function TemplatesPage() {
  await requirePermission('workforce.recruitment_settings.write')
  const db = createSupabaseAdminClient()
  const [templates, versions] = await Promise.all([
    db.from('recruitment_message_templates').select('*').order('name'),
    db.from('recruitment_message_template_versions').select('*').order('version', { ascending: false }),
  ])
  if (templates.error) throw templates.error; if (versions.error) throw versions.error
  return <>
    <WorkforceHeading title="Communication templates" subtitle="English and Kiswahili messages with placeholders, approval status, provider tests and immutable versions." />
    <section className="rounded-2xl border border-violet-100 bg-violet-50 p-5"><h2 className="font-semibold text-violet-950">Create template</h2><form action={createMessageTemplate} className="mt-4 grid gap-3 md:grid-cols-3"><input className={input} name="name" required placeholder="Template name" /><select className={input} name="channel"><option value="email">Email</option><option value="in_app">Candidate portal</option><option value="sms">SMS (when enabled)</option><option value="whatsapp">WhatsApp (formal integration + consent)</option><option value="phone_log">Phone-call log</option></select><select className={input} name="language_code"><option value="en">English</option><option value="sw">Kiswahili</option></select><input className={input} name="category" required placeholder="Category, e.g. interview_invitation" /><input className={`${input} md:col-span-2`} name="subject_template" placeholder="Subject (email only)" /><textarea className={`${input} md:col-span-3`} name="body_template" required rows={5} placeholder="Hello {{candidate.first_name}}, …" /><button className="rounded-lg bg-[#5B2D8E] px-4 py-2 text-xs font-semibold text-white md:col-span-3">Create draft</button></form></section>
    <div className="mt-5 space-y-4">{(templates.data ?? []).map((template) => { const history = (versions.data ?? []).filter((version) => version.template_id === template.id); return <details key={template.id} className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><summary className="cursor-pointer"><span className="font-semibold">{template.name}</span><span className="ml-2 text-xs capitalize text-gray-500">{template.channel.replaceAll('_', ' ')} · {template.language_code} · {template.status} · v{history[0]?.version ?? 1}</span></summary><div className="mt-4 grid gap-4 xl:grid-cols-[1fr_320px]"><div><h3 className="text-sm font-semibold">Edit and preview</h3><form action={updateMessageTemplate.bind(null, template.id)} className="mt-3 space-y-2"><input className={input} name="subject_template" defaultValue={template.subject_template ?? ''} placeholder="Subject" /><textarea className={input} name="body_template" rows={7} defaultValue={template.body_template} required /><input className={input} name="change_summary" required placeholder="Change summary" /><button className="rounded-lg border border-gray-200 px-3 py-2 text-xs font-semibold">Save new version</button></form><div className="mt-4 rounded-xl bg-gray-50 p-4"><p className="text-xs font-semibold uppercase text-gray-500">Preview</p>{template.subject_template && <p className="mt-2 text-sm font-semibold">{template.subject_template}</p>}<p className="mt-2 whitespace-pre-wrap text-sm leading-6">{template.body_template}</p><p className="mt-3 text-xs text-gray-500">Placeholders: {template.variables?.length ? template.variables.map((value: string) => `{{${value}}}`).join(', ') : 'none'}</p></div></div><aside><h3 className="text-sm font-semibold">Approval and test</h3><form action={setMessageTemplateStatus.bind(null, template.id, template.status === 'active' ? 'archived' : 'active')} className="mt-3"><button className="w-full rounded-lg bg-[#5B2D8E] px-3 py-2 text-xs font-semibold text-white">{template.status === 'active' ? 'Archive template' : 'Approve and activate'}</button></form>{template.channel === 'email' && <form action={sendTemplateTest.bind(null, template.id)} className="mt-3 rounded-xl bg-gray-50 p-3"><label className="text-xs font-semibold">Provider test email<input className={`${input} mt-1`} name="address" type="email" required /></label><button className="mt-2 w-full rounded-lg border bg-white px-3 py-2 text-xs font-semibold">Send rendered test</button></form>}<h3 className="mt-4 text-sm font-semibold">Version history</h3><ol className="mt-2 space-y-2">{history.map((version) => <li key={version.id} className="rounded-lg bg-gray-50 px-3 py-2 text-xs"><b>v{version.version}</b> · {version.change_summary ?? 'Revision'}<br /><time className="text-gray-400">{new Date(version.created_at).toLocaleString('en-TZ')}</time></li>)}</ol></aside></div></details> })}</div>
  </>
}
