import Link from 'next/link'
import type { CareersCmsContent } from '@/lib/careers-db'

function href(value: string | null): string | null {
  if (!value) return null
  if (value.startsWith('/')) return value
  try { const url = new URL(value); return ['https:', 'http:'].includes(url.protocol) ? url.toString() : null } catch { return null }
}

export default function CareersManagedContent({ content }: { content: CareersCmsContent }) {
  return <>{content.blocks.map((block, index) => {
    const cta = href(block.ctaHref)
    if (block.blockType === 'hero') return <section key={block.id} className="relative overflow-hidden bg-[#EDE4F2] px-5 py-24 sm:px-8 lg:py-32"><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-black/45">Careers at OpusFesta · Tanzania</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold tracking-tight text-gray-950 sm:text-6xl">{block.heading}</h1><p className="mt-6 max-w-2xl whitespace-pre-wrap text-lg leading-8 text-gray-700">{block.body}</p>{cta && block.ctaLabel && <Link href={cta} className="mt-8 inline-flex rounded-full bg-black px-6 py-3 text-sm font-semibold text-white">{block.ctaLabel}</Link>}</div>{block.imageUrl && <img src={block.imageUrl} alt={block.imageAlt ?? ''} className="aspect-[4/3] w-full rounded-[2rem] object-cover shadow-xl" />}</div></section>
    if (block.blockType === 'benefits') return <section key={block.id} className="px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-semibold tracking-tight">{block.heading || 'Benefits'}</h2>{block.body && <p className="mt-3 max-w-2xl text-gray-600">{block.body}</p>}<div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{content.benefits.map((benefit) => <article key={benefit.id} className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="font-semibold">{benefit.title}</h3><p className="mt-2 text-sm leading-6 text-gray-600">{benefit.description}</p></article>)}</div></div></section>
    if (block.blockType === 'locations') return <section key={block.id} className="bg-[#171717] px-5 py-20 text-white sm:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-semibold">{block.heading || 'Where we work'}</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{content.locations.map((location) => <article key={location.id} className="rounded-2xl bg-white/10 p-6"><h3 className="font-semibold">{location.name}</h3><p className="mt-2 text-sm leading-6 text-white/70">{location.summary || location.address}</p></article>)}</div></div></section>
    if (block.blockType === 'faq') return <section key={block.id} className="px-5 py-20 sm:px-8"><div className="mx-auto max-w-4xl"><h2 className="text-3xl font-semibold">{block.heading || 'Frequently asked questions'}</h2><div className="mt-8 divide-y divide-gray-200">{content.faqs.map((item) => <details key={item.id} className="py-5"><summary className="cursor-pointer font-semibold text-gray-900">{item.question}</summary><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-gray-600">{item.answer}</p></details>)}</div></div></section>
    if (block.blockType === 'story') return <section key={block.id} className="bg-[#FFF7E8] px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-semibold">{block.heading || 'People of OpusFesta'}</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{content.stories.map((story) => <article key={story.id} className="rounded-2xl bg-white p-6"><h3 className="text-xl font-semibold">{story.headline}</h3><p className="mt-3 text-sm leading-6 text-gray-600">{story.body}</p><p className="mt-4 text-xs font-semibold text-gray-500">{story.personName}{story.roleTitle ? ` · ${story.roleTitle}` : ''}</p></article>)}</div></div></section>
    return <section key={block.id} className={index % 2 ? 'bg-white px-5 py-20 sm:px-8' : 'px-5 py-20 sm:px-8'}><div className="mx-auto max-w-5xl">{block.heading && <h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">{block.heading}</h2>}<p className="mt-5 whitespace-pre-wrap text-base leading-8 text-gray-600">{block.body}</p>{block.imageUrl && <img src={block.imageUrl} alt={block.imageAlt ?? ''} className="mt-8 max-h-[560px] w-full rounded-3xl object-cover" />}{cta && block.ctaLabel && <Link href={cta} className="mt-7 inline-flex rounded-full bg-black px-5 py-3 text-sm font-semibold text-white">{block.ctaLabel}</Link>}</div></section>
  })}</>
}
